[package]
name = "mac-parser"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/Frostie314159/mac-parser"
authors = ["Frostie314159"]
description = "A minimal crate for parsing MAC addresses and analysing them."
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
defmt = { version = "1.0.1", optional = true }
heapless = { version = "0.9.3", optional = true, features = ["serde"] }
scroll = { version = "0.13.0", default-features = false }
serde = { version = "1.0.229", optional = true, default-features = false }

[features]
debug = []
default = ["debug"]
defmt = ["dep:defmt"]
serde = ["dep:serde", "dep:heapless"]

[dev-dependencies]
heapless = "0.9.3"
serde_json = { version = "1.0.151", default-features = false, features = ["alloc"] }
